import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#f8f9fa" },
  profileHeader: {
    alignItems: "center",
    paddingVertical: 40,
    backgroundColor: "#fff",
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    elevation: 2,
  },
  avatarContainer: { position: "relative" },
  avatar: {
    width: 100,
    height: 100,
    borderRadius: 50,
    borderWidth: 4,
    borderColor: "#f1f2f6",
  },
  editBadge: {
    position: "absolute",
    bottom: 0,
    right: 0,
    backgroundColor: "#2ecc71",
    padding: 8,
    borderRadius: 20,
    borderWidth: 3,
    borderColor: "#fff",
  },
  userName: { fontSize: 22, fontWeight: "bold", color: "#333", marginTop: 15 },
  userEmail: { fontSize: 14, color: "#999", marginTop: 4 },
  premiumBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#333",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    marginTop: 15,
    gap: 6,
  },
  premiumText: { color: "#f1c40f", fontSize: 12, fontWeight: "bold" },
  section: { marginTop: 25, paddingHorizontal: 20 },
  sectionLabel: {
    fontSize: 13,
    fontWeight: "bold",
    color: "#999",
    marginBottom: 10,
    marginLeft: 5,
    textTransform: "uppercase",
  },
  card: {
    backgroundColor: "#fff",
    borderRadius: 20,
    overflow: "hidden",
    elevation: 1,
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    padding: 15,
  },
  iconWrapper: {
    width: 40,
    height: 40,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 15,
  },
  menuText: { flex: 1 },
  menuTitle: { fontSize: 16, fontWeight: "600", color: "#333" },
  menuSubtitle: { fontSize: 12, color: "#999", marginTop: 2 },
  divider: { height: 1, backgroundColor: "#f1f1f1", marginHorizontal: 15 },
  logoutBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 40,
    padding: 15,
    marginHorizontal: 20,
    backgroundColor: "#fff",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#ff7675",
    gap: 10,
  },
  logoutText: { color: "#e74c3c", fontWeight: "bold", fontSize: 16 },
  footer: { alignItems: "center", marginTop: 30 },
  versionText: { fontSize: 11, color: "#ccc" },
});
