import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#0f0f0f" },
  header: {
    backgroundColor: "#161616",
    padding: 25,
    borderBottomLeftRadius: 35,
    borderBottomRightRadius: 35,
    paddingBottom: 40,
  },
  greeting: { color: "#888", fontSize: 14, fontWeight: "500" },
  balanceContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 20,
  },
  balanceTitle: {
    color: "#555",
    fontSize: 13,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  balanceAmount: {
    color: "#ffffff",
    fontSize: 32,
    fontWeight: "bold",
    marginTop: 5,
  },
  eyeBtn: {
    backgroundColor: "rgba(46, 204, 113, 0.1)",
    padding: 10,
    borderRadius: 12,
  },
  quickReport: {
    flexDirection: "row",
    backgroundColor: "#1e1e1e",
    marginTop: 30,
    borderRadius: 24,
    padding: 18,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#222",
  },
  reportIconBg: { padding: 8, backgroundColor: "#0f0f0f", borderRadius: 12 },
  reportItem: { flex: 1, flexDirection: "row", alignItems: "center" },
  reportDivider: {
    width: 1,
    height: 35,
    backgroundColor: "#333",
    marginHorizontal: 15,
  },
  reportLabel: { color: "#555", fontSize: 10, fontWeight: "bold" },
  reportValue: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 15,
    marginTop: 2,
  },
  content: { paddingHorizontal: 20, marginTop: -25 },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 30,
    marginBottom: 15,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#eee",
    letterSpacing: 0.5,
  },
  seeAll: { color: "#2ecc71", fontSize: 12, fontWeight: "700" },
  sectionHeaderChart: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 15,
  },
  walletScroll: { flexDirection: "row" },
  walletCard: { padding: 20, borderRadius: 28, width: 170, marginRight: 15 },
  walletName: { color: "#888", marginTop: 15, fontSize: 12 },
  walletMoney: {
    color: "#ffffff",
    fontWeight: "bold",
    fontSize: 18,
    marginTop: 4,
  },
  chartCard: {
    backgroundColor: "#161616",
    padding: 20,
    borderRadius: 28,
    marginTop: 10,
    borderWidth: 1,
    borderColor: "#222",
  },
  chartWrapper: { alignItems: "center", marginTop: 10 },
  transCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#161616",
    padding: 18,
    borderRadius: 24,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#222",
  },
  transIcon: {
    width: 50,
    height: 50,
    backgroundColor: "#1e1e1e",
    borderRadius: 18,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 15,
  },
  itemTitle: { fontWeight: "600", color: "#eee", fontSize: 15 },
  itemSub: { color: "#555", fontSize: 12, marginTop: 4 },
  itemAmount: { fontWeight: "bold", fontSize: 15 },
});
