import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F8F9FA" },
  header: {
    backgroundColor: "#FFFFFF",
    padding: 25,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    paddingBottom: 35,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 5,
  },
  greeting: { color: "#95A5A6", fontSize: 14, fontWeight: "500" },
  balanceContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 15,
  },
  balanceTitle: {
    color: "#7F8C8D",
    fontSize: 13,
    letterSpacing: 0.5,
  },
  balanceAmount: {
    color: "#2C3E50",
    fontSize: 32,
    fontWeight: "800",
    marginTop: 5,
  },
  eyeBtn: {
    backgroundColor: "#F1F2F6",
    padding: 10,
    borderRadius: 14,
  },
  quickReport: {
    flexDirection: "row",
    backgroundColor: "#FFFFFF",
    marginTop: 25,
    borderRadius: 20,
    padding: 18,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#F1F2F6",
  },
  reportIconBg: { padding: 8, backgroundColor: "#F8F9FA", borderRadius: 12 },
  reportItem: { flex: 1, flexDirection: "row", alignItems: "center" },
  reportDivider: {
    width: 1,
    height: 30,
    backgroundColor: "#ECF0F1",
    marginHorizontal: 15,
  },
  reportLabel: { color: "#BDC3C7", fontSize: 11, fontWeight: "600" },
  reportValue: {
    color: "#2C3E50",
    fontWeight: "700",
    fontSize: 15,
    marginTop: 2,
  },
  content: { paddingHorizontal: 20, marginTop: 10 },
  sectionHeaderChart: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 25,
    marginBottom: 15,
  },
  sectionTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: "#2C3E50",
  },
  seeAll: { color: "#2ecc71", fontSize: 13, fontWeight: "600" },
  walletCard: {
    padding: 20,
    borderRadius: 24,
    width: 160,
    marginRight: 15,
    backgroundColor: "#FFF",
    borderWidth: 1,
    borderColor: "#F1F2F6",
  },
  walletName: {
    color: "#95A5A6",
    marginTop: 12,
    fontSize: 12,
    fontWeight: "500",
  },
  walletMoney: {
    color: "#2C3E50",
    fontWeight: "700",
    fontSize: 17,
    marginTop: 4,
  },
  walletScroll: { flexDirection: "row" },
  transCard: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: '#FFF',
    borderRadius: 12,
    marginBottom: 8,
  },
  transIcon: {
    width: 45,
    height: 45,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  itemTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: '#1A1A1A',
    marginBottom: 2,
  },
  itemSub: {
    fontSize: 12,
    color: '#999',
  },
  itemAmount: {
    fontSize: 16,
    fontWeight: '700',
  },
  chartCard: {
    backgroundColor: "#161616",
    padding: 20,
    borderRadius: 28,
    marginTop: 10,
    borderWidth: 1,
    borderColor: "#222",
  },
  chartWrapper: {
    marginTop: 15,
    alignItems: "center",
  },
  emptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 40,
  },
  emptyCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#F8F9FA',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  emptyText: {
    color: '#A1A1A1',
    fontSize: 14,
  }
});
